import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pl" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {children}
        <footer>
      <div className="footerLeft">
        <p>&copy; FlexWebs Damian Gapiński 2026</p>
      </div>
      <div className="footerRight">
        <a>Regulamin</a>
        <a>Polityka prywatności</a>
        <a>Kontakt</a>
      </div>
    </footer>
        </body>
    </html>
  );
}
